// @gntik-ai/ui — public API. One export block per component folder (alphabetical).
export { cn } from './utils/cn';
export { tv, type VariantProps } from './utils/tv';
export type { ComponentDoc } from './doc';

// Theme
export { ThemeProvider, useTheme, themeScript, type ThemeMode, type ResolvedTheme, type ThemeProviderProps } from './theme/ThemeProvider';
export { Logo, type LogoProps } from './theme/Logo';
export { presets, gntikPreset, musematicPreset, falconePreset, type BrandPreset } from './theme/presets';

// Components
export * from './components/Accordion';
export * from './components/Alert';
export * from './components/AlertDialog';
export * from './components/AspectRatio';
export * from './components/Avatar';
export * from './components/Badge';
export * from './components/Breadcrumbs';
export * from './components/Button';
export * from './components/Calendar';
export * from './components/Card';
export * from './components/Checkbox';
export * from './components/ChoiceCard';
export * from './components/CodeBlock';
export * from './components/Collapsible';
export * from './components/Combobox';
export * from './components/CommandPalette';
export * from './components/ContextMenu';
export * from './components/DatePicker';
export * from './components/Dialog';
export * from './components/Drawer';
export * from './components/EmptyState';
export * from './components/Field';
export * from './components/Grid';
export * from './components/HoverCard';
export * from './components/InfoTip';
export * from './components/Input';
export * from './components/JsonViewer';
export * from './components/Kbd';
export * from './components/Link';
export * from './components/Menu';
export * from './components/Meter';
export * from './components/MobileNav';
export * from './components/MultiSelect';
export * from './components/NavList';
export * from './components/NotificationsPopover';
export * from './components/NumberInput';
export * from './components/OtpInput';
export * from './components/OverflowList';
export * from './components/Pagination';
export * from './components/PasswordInput';
export * from './components/Popover';
export * from './components/Progress';
export * from './components/RadioGroup';
export * from './components/Resizable';
export * from './components/ScrollArea';
export * from './components/Section';
export * from './components/Select';
export * from './components/Separator';
export * from './components/Skeleton';
export * from './components/Slider';
export * from './components/Sparkline';
export * from './components/Spinner';
export * from './components/Stack';
export * from './components/StatusDot';
export * from './components/StatusTag';
export * from './components/Stepper';
export * from './components/Switch';
export * from './components/Table';
export * from './components/Tabs';
export * from './components/Text';
export * from './components/Textarea';
export * from './components/ThemeSwitcher';
export * from './components/Thumbnail';
export * from './components/Timer';
export * from './components/Timestamp';
export * from './components/Toast';
export * from './components/ToggleGroup';
export * from './components/Token';
export * from './components/TokenInput';
export * from './components/Toolbar';
export * from './components/Tooltip';
export * from './components/TreeList';
export * from './components/UserMenu';
export * from './components/VisuallyHidden';
export * from './components/WorkspaceSwitcher';
