/**
 * Builds INVENTORY.md (repo root) from the two sources of truth: the catalog inventory
 * (apps/docs/src/catalog/registry.jsx) and kit-registry.json (packages). `--check` fails when stale.
 */
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '../../..');
const OUT = path.join(ROOT, 'INVENTORY.md');

interface KitItem { id: string; kind: string; name: string; package: string; group: string; status: string }

const catalogSrc = fs.readFileSync(path.join(ROOT, 'apps/docs/src/catalog/registry.jsx'), 'utf8');
const groups: { group: string; items: { id: string; label: string; status: string }[] }[] = [];
for (const g of catalogSrc.matchAll(/\{\s*group:\s*'([^']+)'[\s\S]*?items:\s*\[([\s\S]*?)\]\s*\}/g)) {
  const items = [...g[2]!.matchAll(/id:\s*'([^']+)',\s*label:\s*'([^']+)'[\s\S]*?status:\s*'([^']+)'/g)].map((m) => ({ id: m[1]!, label: m[2]!, status: m[3]! }));
  groups.push({ group: g[1]!, items });
}
const kit = (JSON.parse(fs.readFileSync(path.join(ROOT, 'kit-registry.json'), 'utf8')) as { items: KitItem[] }).items;

const total = groups.reduce((n, g) => n + g.items.length, 0);
const done = groups.reduce((n, g) => n + g.items.filter((i) => i.status === 'done').length, 0);
const byKind = (kind: string) => kit.filter((i) => i.kind === kind);
const table = (items: KitItem[], key: (i: KitItem) => string) => {
  const map = new Map<string, KitItem[]>();
  for (const i of items) map.set(key(i), [...(map.get(key(i)) ?? []), i]);
  return [...map.entries()].sort(([a], [b]) => a.localeCompare(b))
    .map(([k, list]) => `| ${k} | ${list.map((i) => i.name).sort().join(' · ')} | ${list.length} |`).join('\n');
};

const md = `# Gntik UI — inventory

Generated by \`pnpm registry\` from \`apps/docs/src/catalog/registry.jsx\` (the catalog) and
\`kit-registry.json\` (the packages). Do not edit by hand.

## Catalog: **${done} / ${total} done**

| Group | Entries |
| --- | --- |
${groups.map((g) => `| ${g.group} | ${g.items.map((i) => i.label + (i.status === 'done' ? '' : ` (${i.status})`)).join(' · ')} |`).join('\n')}

## Packages: ${byKind('component').length} components · ${byKind('layout').length} layouts · ${byKind('block').length} blocks · ${byKind('template').length} templates

### Components (@gntik-ai/ui, @gntik-ai/chat)

| Group | Components | Count |
| --- | --- | --- |
${table(byKind('component'), (i) => (i.package === '@gntik-ai/chat' ? 'Chat' : i.group || 'Other'))}

### Layouts (@gntik-ai/ui)

${byKind('layout').map((i) => i.name).sort().join(' · ')}

### Blocks (@gntik-ai/blocks)

| Family | Blocks | Count |
| --- | --- | --- |
${table(byKind('block'), (i) => i.group)}

### Page templates (@gntik-ai/templates)

| Family | Templates | Count |
| --- | --- | --- |
${table(byKind('template'), (i) => i.group)}
`;

if (process.argv.includes('--check')) {
  if ((fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '') !== md) {
    console.error('INVENTORY.md is stale — run `pnpm registry`.');
    process.exit(1);
  }
  console.log('INVENTORY.md is up to date.');
} else {
  fs.writeFileSync(OUT, md);
  console.log(`INVENTORY.md written: catalog ${done}/${total}, ${kit.length} kit items.`);
}
