/* ============================================================================
   gntik-ui-mcp · kit.ts — the installable kit (kit-registry.json)
   ----------------------------------------------------------------------------
   kit-registry.json (repo root, generated by `pnpm registry`) lists every
   component and layout (@gntik-ai/ui, @gntik-ai/chat), block (@gntik-ai/blocks)
   and page template (@gntik-ai/templates) with its source files and deps.
   This module loads it, reads each item's *.doc.ts / *.meta.ts WITHOUT
   executing it, resolves the public export name and builds a usage snippet.
   Shared by the MCP tools (kit-tools.ts) and scripts/build-llms.ts.
   ============================================================================ */
import fs from 'node:fs';
import path from 'node:path';

export const KIT_REGISTRY_FILE = 'kit-registry.json';
export const REPO_BLOB = 'https://github.com/gntik-ai/gntik-ui/blob/main/';
export const KIT_KINDS = ['component', 'layout', 'block', 'template'] as const;
export type KitKind = (typeof KIT_KINDS)[number];

export interface KitFile {
  path: string;
  target: string;
}

export interface KitItem {
  id: string;
  kind: KitKind;
  name: string;
  package: string;
  group: string;
  status: string;
  description: string;
  files: KitFile[];
  dependencies: string[];
  registryDependencies: string[];
  docs?: string;
}

export interface KitRegistry {
  root: string;
  items: KitItem[];
  byId: Map<string, KitItem>;
}

/** What the *.doc.ts (components, layouts) or *.meta.ts (blocks, templates) file declares. */
export interface DocInfo {
  primitive?: string;
  pattern?: string;
  keyboard: Array<[key: string, behaviour: string]>;
  tokens: string[];
  /** Blocks: kit components it composes. */
  uses: string[];
  /** Templates: layout it is built on. */
  layout?: string;
  /** Templates: block ids it composes. */
  blocks: string[];
  priority?: string;
}

/* ── loading ──────────────────────────────────────────────────────────────── */

const cache = new Map<string, { mtime: number; kit: KitRegistry }>();

/** Loads kit-registry.json from `root` (cached until the file changes). Empty when absent. */
export function loadKit(root: string): KitRegistry {
  const file = path.join(root, KIT_REGISTRY_FILE);
  let mtime: number;
  try {
    mtime = fs.statSync(file).mtimeMs;
  } catch {
    mtime = -1;
  }
  const hit = cache.get(root);
  if (hit && hit.mtime === mtime) return hit.kit;
  let items: KitItem[] = [];
  if (mtime >= 0) {
    const parsed = JSON.parse(fs.readFileSync(file, 'utf8')) as { items?: KitItem[] };
    items = parsed.items ?? [];
  }
  const kit: KitRegistry = { root, items, byId: new Map(items.map((i) => [i.id, i])) };
  cache.set(root, { mtime, kit });
  return kit;
}

/** Reads a repo-relative file, or undefined when the deployment does not ship sources. */
export function readRepoFile(root: string, rel: string): string | undefined {
  const file = path.join(root, rel);
  try {
    return fs.readFileSync(file, 'utf8');
  } catch {
    return undefined;
  }
}

/* ── *.doc.ts / *.meta.ts parsing (no execution) ──────────────────────────── */

const STR = String.raw`(?:'((?:[^'\\]|\\.)*)'|"((?:[^"\\]|\\.)*)"|\x60((?:[^\x60\\]|\\.)*)\x60)`;
const unescape = (s: string) => s.replace(/\\(.)/g, '$1');
const strOf = (m: RegExpMatchArray, from = 1) => unescape(m[from] ?? m[from + 1] ?? m[from + 2] ?? '');

/** Body of `name: [ … ]`, bracket- and string-aware. */
function arrayBody(text: string, name: string): string | undefined {
  const start = new RegExp(`\\b${name}\\s*:\\s*\\[`).exec(text);
  if (!start) return undefined;
  let depth = 1;
  let i = start.index + start[0].length;
  for (; i < text.length && depth > 0; i++) {
    const c = text[i];
    if (c === '[') depth++;
    else if (c === ']') depth--;
    else if (c === "'" || c === '"' || c === '`') {
      for (i++; i < text.length && text[i] !== c; i++) if (text[i] === '\\') i++;
    }
  }
  return text.slice(start.index + start[0].length, i - 1);
}

const stringList = (body: string | undefined) =>
  body === undefined ? [] : [...body.matchAll(new RegExp(STR, 'g'))].map((m) => strOf(m));

export function parseDocInfo(text: string): DocInfo {
  const field = (name: string) => {
    const m = new RegExp(`\\b${name}\\s*:\\s*${STR}`).exec(text);
    return m ? strOf(m) : undefined;
  };
  const keyboard: DocInfo['keyboard'] = [];
  const kb = arrayBody(text, 'keyboard');
  if (kb !== undefined) {
    const row = new RegExp(String.raw`\[\s*${STR}\s*,\s*${STR}\s*,?\s*\]`, 'g');
    for (const m of kb.matchAll(row)) keyboard.push([strOf(m, 1), strOf(m, 4)]);
  }
  return {
    primitive: field('primitive'),
    pattern: field('pattern'),
    keyboard,
    tokens: stringList(arrayBody(text, 'tokens')),
    uses: stringList(arrayBody(text, 'uses')),
    layout: field('layout'),
    blocks: stringList(arrayBody(text, 'blocks')),
    priority: field('priority'),
  };
}

export function docInfoOf(root: string, item: KitItem): DocInfo {
  const text = item.docs ? readRepoFile(root, item.docs) : undefined;
  return text ? parseDocInfo(text) : { keyboard: [], tokens: [], uses: [], blocks: [] };
}

/* ── export names + usage ─────────────────────────────────────────────────── */

const pascal = (id: string) => id.split(/[-_\s]+/).map((p) => p.charAt(0).toUpperCase() + p.slice(1)).join('');
const itemDir = (item: KitItem) => (item.docs ? path.posix.dirname(item.docs) : undefined);

/** True when `export interface <name>Props` declares a member without `?` (it cannot render bare). */
export function hasRequiredProps(src: string, name: string): boolean {
  const start = new RegExp(`export interface ${name}Props\\b[^{]*\\{`).exec(src);
  if (!start) return false;
  let depth = 1;
  let i = start.index + start[0].length;
  for (; i < src.length && depth > 0; i++) {
    if (src[i] === '{') depth++;
    else if (src[i] === '}') depth--;
  }
  return /^ {2}(?:readonly\s+)?\w+:/m.test(src.slice(start.index + start[0].length, i - 1));
}

/** PascalCase components a block's main file exports: the folder-named one first, unless it needs props. */
function blockExports(root: string, item: KitItem): string[] {
  const dir = itemDir(item);
  if (!dir) return [];
  const folder = path.posix.basename(dir);
  const src = readRepoFile(root, `${dir}/${folder}.tsx`) ?? '';
  const names = [...src.matchAll(/^export (?:function|const) ([A-Z]\w*)/gm)].map((m) => m[1] ?? '');
  if (!names.length) return [folder];
  const ordered = names.includes(folder) ? [folder, ...names.filter((n) => n !== folder)] : names;
  const bare = ordered.find((n) => !hasRequiredProps(src, n));
  return bare ? [bare, ...ordered.filter((n) => n !== bare)] : ordered;
}

/** Public export name(s) of an item, primary first. */
export function exportNamesOf(root: string, item: KitItem): string[] {
  if (item.kind === 'block') return blockExports(root, item);
  if (item.kind === 'template') {
    const index = readRepoFile(root, 'packages/templates/src/index.ts') ?? '';
    const m = new RegExp(`export \\{ default as (\\w+) \\} from '\\./${item.id}/Page'`).exec(index);
    return [m?.[1] ?? `${pascal(item.id)}Page`];
  }
  if (item.id === 'ui-utils') return ['cn', 'tv'];
  return [/^[A-Z]\w*$/.test(item.name) ? item.name : pascal(item.id)];
}

export function exportNameOf(root: string, item: KitItem): string {
  return exportNamesOf(root, item)[0] ?? pascal(item.id);
}

/** Templates whose Page renders inside the shared ConsoleShell (they take a `shell` prop). */
export function usesConsoleShell(root: string, item: KitItem): boolean {
  if (item.kind !== 'template') return false;
  const src = readRepoFile(root, `packages/templates/src/${item.id}/Page.tsx`) ?? '';
  return /from '\.\.\/shared\/ConsoleShell'/.test(src) && /\bshell\b/.test(src);
}

/** Rewrites an example's relative imports to the item's package and lucide to @gntik-ai/icons. */
export function toPackageImports(code: string, pkg: string): string {
  return code
    .replace(/from '\.{1,2}\/[^']*'/g, `from '${pkg}'`)
    .replace(/from 'lucide-react'/g, "from '@gntik-ai/icons'");
}

export interface Usage {
  /** "example" = a real examples/*.tsx file; "generated" = an import + JSX sketch. */
  source: 'example' | 'generated';
  file?: string;
  code: string;
}

export function usageOf(root: string, item: KitItem): Usage {
  const dir = itemDir(item);
  const name = exportNameOf(root, item);
  if ((item.kind === 'component' || item.kind === 'layout') && dir) {
    const exDir = path.join(root, dir, 'examples');
    const first = fs.existsSync(exDir) ? fs.readdirSync(exDir).filter((f) => f.endsWith('.tsx')).sort()[0] : undefined;
    const code = first ? readRepoFile(root, `${dir}/examples/${first}`) : undefined;
    if (first && code) return { source: 'example', file: `${dir}/examples/${first}`, code: toPackageImports(code, item.package) };
  }
  if (item.kind === 'template') {
    const shell = usesConsoleShell(root, item);
    return {
      source: 'generated',
      code: [
        `import { ${name} } from '@gntik-ai/templates';`,
        '',
        '// Every prop is optional: unset ones fall back to the template fixtures.',
        shell
          ? `export default function Route() {\n  return <${name} shell={{ currentHref: '/', nav: undefined /* your NavGroup[] */ }} />;\n}`
          : `export default function Route() {\n  return <${name} />;\n}`,
      ].join('\n'),
    };
  }
  if (item.kind === 'block') {
    return {
      source: 'generated',
      code: `import { ${name} } from '@gntik-ai/blocks';\n\n// Props default to the block fixtures; pass your data.\n<${name} />`,
    };
  }
  if (item.id === 'ui-utils') return { source: 'generated', code: "import { cn } from '@gntik-ai/ui';" };
  return { source: 'generated', code: `import { ${name} } from '${item.package}';\n\n<${name} />` };
}

/* ── filtering + search ───────────────────────────────────────────────────── */

export interface KitFilter {
  kind?: string;
  group?: string;
  query?: string;
}

function termScore(term: string, item: KitItem): number {
  const id = item.id.toLowerCase();
  const name = item.name.toLowerCase();
  const group = item.group.toLowerCase();
  const desc = item.description.toLowerCase();
  if (id === term || name === term) return 100;
  if (id.startsWith(term) || name.startsWith(term)) return 80;
  if (id.includes(term) || name.includes(term)) return 60;
  if (group.includes(term)) return 40;
  if (desc.includes(term)) return 20;
  return 0;
}

/** Filters by kind/group; a query keeps items where every term matches, best first. */
export function filterKit(items: KitItem[], f: KitFilter): KitItem[] {
  const kind = f.kind?.toLowerCase();
  const group = f.group?.toLowerCase();
  const pool = items.filter((i) => (!kind || i.kind === kind) && (!group || i.group.toLowerCase() === group));
  const terms = (f.query ?? '').toLowerCase().split(/\s+/).filter(Boolean);
  if (!terms.length) return pool;
  return pool
    .map((item) => {
      const scores = terms.map((t) => termScore(t, item));
      return { item, score: scores.every((s) => s > 0) ? scores.reduce((a, b) => a + b, 0) : 0 };
    })
    .filter((r) => r.score > 0)
    .sort((a, b) => b.score - a.score || a.item.id.localeCompare(b.item.id))
    .map((r) => r.item);
}

/** Closest ids for a "did you mean" hint. */
export function nearIds(kit: KitRegistry, id: string, kind?: KitKind, n = 5): string[] {
  const parts = id.toLowerCase().split(/[-_\s]+/).filter((p) => p.length > 1);
  const pool = kit.items.filter((i) => !kind || i.kind === kind);
  return pool
    .map((i) => ({ id: i.id, score: parts.reduce((s, p) => s + (i.id.includes(p) || i.name.toLowerCase().includes(p) ? 1 : 0), 0) }))
    .filter((r) => r.score > 0)
    .sort((a, b) => b.score - a.score || a.id.localeCompare(b.id))
    .slice(0, n)
    .map((r) => r.id);
}

/** Leading sentence(s) of a description for one-line listings: at least ~40 characters. */
export function firstSentence(text: string): string {
  const clean = text.replace(/\s+/g, ' ').trim();
  const sentences = clean.match(/[^.!?]+[.!?]+(?=\s|$)/g) ?? [clean];
  let out = '';
  for (const s of sentences) {
    out = `${out} ${s.trim()}`.trim();
    if (out.length >= 40) break;
  }
  return out || clean;
}
